name: Vikash
favicon: null
layout_spectrum: 0.54172328626737
typography_spectrum: 0.20712649240158498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5731741327326745
  lightness: 0.2380374143831432
  saturation: 0.9667706061154604
  rhythmicContrast: 0.8629111896734685
purpose: []
